package identity

type Permission string

const (
	OrganizationsReadPermission            Permission = "organizations:read"
	OrganizationsWritePermission           Permission = "organizations:write"
	WorkspacesReadPermission               Permission = "workspaces:read"
	WorkspacesWritePermission              Permission = "workspaces:write"
	WorkspacesCreatePermission             Permission = "workspaces:create"
	OrganizationMembershipsReadPermission  Permission = "organization_memberships:read"
	OrganizationMembershipsWritePermission Permission = "organization_memberships:write"
	WorkspaceMembershipsReadPermission     Permission = "workspace_memberships:read"
	WorkspaceMembershipsWritePermission    Permission = "workspace_memberships:write"
	ComponentsReadPermission               Permission = "components:read"
	ComponentsWritePermission              Permission = "components:write"
	ReleasesReadPermission                 Permission = "releases:read"
	ReleasesWritePermission                Permission = "releases:write"
	ReleasesCreatePermission               Permission = "releases:create"
	VersionsReadPermission                 Permission = "versions:read"
	VersionsCreatePermission               Permission = "versions:create"
	EnvironmentsReadPermission             Permission = "environments:read"
	EnvironmentsWritePermission            Permission = "environments:write"
	DeploymentsReadPermission              Permission = "deployments:read"
	DeploymentsCreatePermission            Permission = "deployments:create"
	DeploymentsCancelPermission            Permission = "deployments:cancel"
	ExecutionsClaimPermission              Permission = "executions:claim"
	ExecutionsReportStatusPermission       Permission = "executions:report_status"
	DeploymentRunnersWritePermission       Permission = "deployment_runners:write"
	PublishersWritePermission              Permission = "publishers:write"
	PrincipalsReadPermission               Permission = "principals:read"
	PrincipalsWritePermission              Permission = "principals:write"
	RolesReadPermission                    Permission = "roles:read"
	RolesWritePermission                   Permission = "roles:write"
	WebhooksReadPermission                 Permission = "webhooks:read"
	WebhooksWritePermission                Permission = "webhooks:write"
	WebhookDeliveriesReadPermission        Permission = "webhook_deliveries:read"
	WebhookDeliveriesRetryPermission       Permission = "webhook_deliveries:retry"
	EventsReadPermission                   Permission = "events:read"
	TagDefinitionsReadPermission           Permission = "tag_definitions:read"
)
