from typing import Protocol

from src.domain.models import (
    Component,
    DeploymentExecution,
    DeploySet,
    Environment,
    EnvironmentState,
    EnvironmentTarget,
    Release,
    TargetResolution,
)


class ComponentRepository(Protocol):
    def get(self, component_id: str) -> Component | None: ...
    def list(self) -> list[Component]: ...
    def put(self, component: Component) -> None: ...


class ReleaseRepository(Protocol):
    def get(self, component_id: str, version: str) -> Release | None: ...
    def create(self, release: Release) -> None: ...
    def list_by_component(self, component_id: str | None = None) -> list[Release]: ...


class DeploySetRepository(Protocol):
    def get(self, deployset_id: str) -> DeploySet | None: ...
    def create(self, deployset: DeploySet) -> None: ...
    def list(self) -> list[DeploySet]: ...


class EnvironmentRepository(Protocol):
    def get(self, environment_id: str) -> Environment | None: ...
    def list(self) -> list[Environment]: ...
    def put(self, environment: Environment) -> None: ...


class EnvironmentTargetRepository(Protocol):
    def get(self, environment_id: str, component_id: str) -> EnvironmentTarget | None: ...
    def list_by_environment(self, environment_id: str | None = None) -> list[EnvironmentTarget]: ...
    def put(self, target: EnvironmentTarget) -> None: ...


class TargetResolutionRepository(Protocol):
    def get(self, component_type: str, target_key: str) -> TargetResolution | None: ...
    def list_by_type(self, component_type: str | None = None) -> list[TargetResolution]: ...
    def put(self, resolution: TargetResolution) -> None: ...


class EnvironmentStateRepository(Protocol):
    def get(self, environment_id: str) -> EnvironmentState | None: ...
    def list(self) -> list[EnvironmentState]: ...
    def put(self, state: EnvironmentState) -> None: ...


class DeploymentExecutionRepository(Protocol):
    def get(self, deployment_execution_id: str) -> DeploymentExecution | None: ...
    def create(self, execution: DeploymentExecution) -> None: ...
    def list_by_environment(self, environment_id: str | None = None) -> list[DeploymentExecution]: ...
    def latest_for_environment(self, environment_id: str) -> DeploymentExecution | None: ...


class ArtifactResolver(Protocol):
    def resolve(
        self,
        *,
        component_type: str,
        component_id: str,
        version: str,
        artifact_sha256: str,
    ) -> object: ...


class ActualShaReader(Protocol):
    def read_actual_sha256(self, *, component_type: str, target_key: str) -> str | None: ...


class Clock(Protocol):
    def now(self) -> str: ...


class IdGenerator(Protocol):
    def new_id(self) -> str: ...

