from typing import Protocol

from src.domain.models import (
    Component,
    ComponentSet,
    DeploymentExecution,
    DeploymentRunner,
    DeploySet,
    Environment,
    EnvironmentState,
    BootstrapState,
    Principal,
    Release,
    ReleaseSource,
)


class ComponentRepository(Protocol):
    def get(self, component_id: str) -> Component | None: ...
    def list(self) -> list[Component]: ...
    def put(self, component: Component) -> None: ...


class ComponentSetRepository(Protocol):
    def get(self, component_set_id: str) -> ComponentSet | None: ...
    def list(self) -> list[ComponentSet]: ...
    def put(self, component_set: ComponentSet) -> None: ...


class ReleaseRepository(Protocol):
    def get(self, component_id: str, version: str) -> Release | None: ...
    def create(self, release: Release) -> None: ...
    def list_by_component(self, component_id: str | None = None) -> list[Release]: ...


class ReleaseSourceRepository(Protocol):
    def get(self, release_source_id: str) -> ReleaseSource | None: ...
    def list(self) -> list[ReleaseSource]: ...
    def put(self, release_source: ReleaseSource) -> None: ...


class DeploySetRepository(Protocol):
    def get(self, deployset_id: str) -> DeploySet | None: ...
    def create(self, deployset: DeploySet) -> None: ...
    def list(self) -> list[DeploySet]: ...


class EnvironmentRepository(Protocol):
    def get(self, environment_id: str) -> Environment | None: ...
    def list(self) -> list[Environment]: ...
    def put(self, environment: Environment) -> None: ...


class DeploymentRunnerRepository(Protocol):
    def get(self, runner_id: str) -> DeploymentRunner | None: ...
    def list(self) -> list[DeploymentRunner]: ...
    def put(self, runner: DeploymentRunner) -> None: ...


class PrincipalRepository(Protocol):
    def get(self, principal_id: str) -> Principal | None: ...
    def get_by_oidc(self, external_issuer: str, external_subject: str) -> Principal | None: ...
    def list(self) -> list[Principal]: ...
    def put(self, principal: Principal) -> None: ...


class BootstrapStateRepository(Protocol):
    def get(self) -> BootstrapState: ...
    def put(self, state: BootstrapState) -> None: ...


class EnvironmentStateRepository(Protocol):
    def get(self, environment_id: str) -> EnvironmentState | None: ...
    def list(self) -> list[EnvironmentState]: ...
    def put(self, state: EnvironmentState) -> None: ...


class DeploymentExecutionRepository(Protocol):
    def get(self, deployment_execution_id: str) -> DeploymentExecution | None: ...
    def create(self, execution: DeploymentExecution) -> None: ...
    def put(self, execution: DeploymentExecution) -> None: ...
    def list_by_environment(self, environment_id: str | None = None) -> list[DeploymentExecution]: ...
    def latest_for_environment(self, environment_id: str) -> DeploymentExecution | None: ...
    def list_pending(self) -> list[DeploymentExecution]: ...


class Clock(Protocol):
    def now(self) -> str: ...


class IdGenerator(Protocol):
    def new_id(self) -> str: ...


