from typing import Protocol

from src.domain.models import (
    Component,
    ComponentSet,
    DeploymentExecution,
    DeploymentRunner,
    DeploySet,
    Environment,
    EnvironmentState,
    EventLogEntry,
    BootstrapState,
    Organization,
    OrganizationMembership,
    Principal,
    Release,
    Publisher,
    Role,
    TagDefinition,
    Workspace,
    WorkspaceMembership,
    Webhook,
    WebhookDelivery,
)


class OrganizationRepository(Protocol):
    def get(self, organization_id: str) -> Organization | None: ...
    def list(self) -> list[Organization]: ...
    def put(self, organization: Organization) -> None: ...


class WorkspaceRepository(Protocol):
    def get(self, workspace_id: str) -> Workspace | None: ...
    def list(self, organization_id: str | None = None) -> list[Workspace]: ...
    def put(self, workspace: Workspace) -> None: ...


class TagDefinitionRepository(Protocol):
    def get(self, tag_definition_id: str, workspace_id: str = "default") -> TagDefinition | None: ...
    def list(self, workspace_id: str = "default") -> list[TagDefinition]: ...
    def put(self, tag_definition: TagDefinition) -> None: ...


class OrganizationMembershipRepository(Protocol):
    def get(self, organization_id: str, principal_id: str) -> OrganizationMembership | None: ...
    def list(self, organization_id: str | None = None, principal_id: str | None = None) -> list[OrganizationMembership]: ...
    def put(self, membership: OrganizationMembership) -> None: ...


class WorkspaceMembershipRepository(Protocol):
    def get(self, workspace_id: str, principal_id: str) -> WorkspaceMembership | None: ...
    def list(self, workspace_id: str | None = None, principal_id: str | None = None) -> list[WorkspaceMembership]: ...
    def put(self, membership: WorkspaceMembership) -> None: ...


class ComponentRepository(Protocol):
    def get(self, component_id: str, workspace_id: str = "default") -> Component | None: ...
    def list(self, workspace_id: str = "default") -> list[Component]: ...
    def put(self, component: Component) -> None: ...


class ComponentSetRepository(Protocol):
    def get(self, component_set_id: str, workspace_id: str = "default") -> ComponentSet | None: ...
    def list(self, workspace_id: str = "default") -> list[ComponentSet]: ...
    def put(self, component_set: ComponentSet) -> None: ...


class ReleaseRepository(Protocol):
    def get(self, component_id: str, version: str, workspace_id: str = "default") -> Release | None: ...
    def create(self, release: Release) -> None: ...
    def list_by_component(self, component_id: str | None = None, workspace_id: str = "default") -> list[Release]: ...


class PublisherRepository(Protocol):
    def get(self, publisher_id: str, workspace_id: str = "default") -> Publisher | None: ...
    def list(self, workspace_id: str = "default") -> list[Publisher]: ...
    def put(self, publisher: Publisher) -> None: ...


class DeploySetRepository(Protocol):
    def get(self, deployset_id: str, workspace_id: str = "default") -> DeploySet | None: ...
    def create(self, deployset: DeploySet) -> None: ...
    def list(self, workspace_id: str = "default") -> list[DeploySet]: ...


class EnvironmentRepository(Protocol):
    def get(self, environment_id: str, workspace_id: str = "default") -> Environment | None: ...
    def list(self, workspace_id: str = "default") -> list[Environment]: ...
    def put(self, environment: Environment) -> None: ...


class DeploymentRunnerRepository(Protocol):
    def get(self, runner_id: str, workspace_id: str = "default") -> DeploymentRunner | None: ...
    def list(self, workspace_id: str = "default") -> list[DeploymentRunner]: ...
    def put(self, runner: DeploymentRunner) -> None: ...


class PrincipalRepository(Protocol):
    def get(self, principal_id: str) -> Principal | None: ...
    def get_by_oidc(self, external_issuer: str, external_subject: str) -> Principal | None: ...
    def list(self) -> list[Principal]: ...
    def put(self, principal: Principal) -> None: ...


class RoleRepository(Protocol):
    def get(self, role_id: str, workspace_id: str = "default") -> Role | None: ...
    def list(self, workspace_id: str = "default") -> list[Role]: ...
    def put(self, role: Role) -> None: ...


class BootstrapStateRepository(Protocol):
    def get(self) -> BootstrapState: ...
    def put(self, state: BootstrapState) -> None: ...


class EnvironmentStateRepository(Protocol):
    def get(self, environment_id: str, workspace_id: str = "default") -> EnvironmentState | None: ...
    def list(self, workspace_id: str = "default") -> list[EnvironmentState]: ...
    def put(self, state: EnvironmentState) -> None: ...


class DeploymentExecutionRepository(Protocol):
    def get(self, deployment_execution_id: str, workspace_id: str = "default") -> DeploymentExecution | None: ...
    def create(self, execution: DeploymentExecution) -> None: ...
    def put(self, execution: DeploymentExecution) -> None: ...
    def list_by_environment(self, environment_id: str | None = None, workspace_id: str = "default") -> list[DeploymentExecution]: ...
    def latest_for_environment(self, environment_id: str, workspace_id: str = "default") -> DeploymentExecution | None: ...
    def list_pending(self, workspace_id: str = "default") -> list[DeploymentExecution]: ...


class EventLogRepository(Protocol):
    def append(self, event: EventLogEntry) -> None: ...
    def get(self, event_id: str) -> EventLogEntry | None: ...
    def list(
        self,
        *,
        limit: int = 50,
        cursor: str | None = None,
        actor_principal_id: str | None = None,
        resource_type: str | None = None,
        resource_id: str | None = None,
        category: str | None = None,
        action: str | None = None,
        origin: str | None = None,
        from_time: str | None = None,
        to_time: str | None = None,
    ) -> tuple[list[EventLogEntry], str | None]: ...


class WebhookRepository(Protocol):
    def get(self, webhook_id: str, workspace_id: str = "default") -> Webhook | None: ...
    def list(self, workspace_id: str = "default") -> list[Webhook]: ...
    def put(self, webhook: Webhook) -> None: ...


class WebhookDeliveryRepository(Protocol):
    def get(self, webhook_delivery_id: str, workspace_id: str = "default") -> WebhookDelivery | None: ...
    def list(
        self,
        *,
        webhook_id: str | None = None,
        event_id: str | None = None,
        status: str | None = None,
        resource_type: str | None = None,
        resource_id: str | None = None,
        workspace_id: str = "default",
    ) -> list[WebhookDelivery]: ...
    def put(self, delivery: WebhookDelivery) -> None: ...


class Clock(Protocol):
    def now(self) -> str: ...


class IdGenerator(Protocol):
    def new_id(self) -> str: ...
