from typing import Protocol

from src.domain.models import (
    Component,
    ComponentSet,
    DeploymentExecution,
    DeploymentRunner,
    DeploySet,
    Environment,
    EnvironmentState,
    EventLogEntry,
    BootstrapState,
    Principal,
    Release,
    ReleaseSource,
    Role,
    Webhook,
    WebhookDelivery,
)


class ComponentRepository(Protocol):
    def get(self, component_id: str) -> Component | None: ...
    def list(self) -> list[Component]: ...
    def put(self, component: Component) -> None: ...


class ComponentSetRepository(Protocol):
    def get(self, component_set_id: str) -> ComponentSet | None: ...
    def list(self) -> list[ComponentSet]: ...
    def put(self, component_set: ComponentSet) -> None: ...


class ReleaseRepository(Protocol):
    def get(self, component_id: str, version: str) -> Release | None: ...
    def create(self, release: Release) -> None: ...
    def list_by_component(self, component_id: str | None = None) -> list[Release]: ...


class ReleaseSourceRepository(Protocol):
    def get(self, release_source_id: str) -> ReleaseSource | None: ...
    def list(self) -> list[ReleaseSource]: ...
    def put(self, release_source: ReleaseSource) -> None: ...


class DeploySetRepository(Protocol):
    def get(self, deployset_id: str) -> DeploySet | None: ...
    def create(self, deployset: DeploySet) -> None: ...
    def list(self) -> list[DeploySet]: ...


class EnvironmentRepository(Protocol):
    def get(self, environment_id: str) -> Environment | None: ...
    def list(self) -> list[Environment]: ...
    def put(self, environment: Environment) -> None: ...


class DeploymentRunnerRepository(Protocol):
    def get(self, runner_id: str) -> DeploymentRunner | None: ...
    def list(self) -> list[DeploymentRunner]: ...
    def put(self, runner: DeploymentRunner) -> None: ...


class PrincipalRepository(Protocol):
    def get(self, principal_id: str) -> Principal | None: ...
    def get_by_oidc(self, external_issuer: str, external_subject: str) -> Principal | None: ...
    def list(self) -> list[Principal]: ...
    def put(self, principal: Principal) -> None: ...


class RoleRepository(Protocol):
    def get(self, role_id: str) -> Role | None: ...
    def list(self) -> list[Role]: ...
    def put(self, role: Role) -> None: ...


class BootstrapStateRepository(Protocol):
    def get(self) -> BootstrapState: ...
    def put(self, state: BootstrapState) -> None: ...


class EnvironmentStateRepository(Protocol):
    def get(self, environment_id: str) -> EnvironmentState | None: ...
    def list(self) -> list[EnvironmentState]: ...
    def put(self, state: EnvironmentState) -> None: ...


class DeploymentExecutionRepository(Protocol):
    def get(self, deployment_execution_id: str) -> DeploymentExecution | None: ...
    def create(self, execution: DeploymentExecution) -> None: ...
    def put(self, execution: DeploymentExecution) -> None: ...
    def list_by_environment(self, environment_id: str | None = None) -> list[DeploymentExecution]: ...
    def latest_for_environment(self, environment_id: str) -> DeploymentExecution | None: ...
    def list_pending(self) -> list[DeploymentExecution]: ...


class EventLogRepository(Protocol):
    def append(self, event: EventLogEntry) -> None: ...
    def get(self, event_id: str) -> EventLogEntry | None: ...
    def list(
        self,
        *,
        limit: int = 50,
        cursor: str | None = None,
        actor_principal_id: str | None = None,
        resource_type: str | None = None,
        resource_id: str | None = None,
        category: str | None = None,
        action: str | None = None,
        origin: str | None = None,
        from_time: str | None = None,
        to_time: str | None = None,
    ) -> tuple[list[EventLogEntry], str | None]: ...


class WebhookRepository(Protocol):
    def get(self, webhook_id: str) -> Webhook | None: ...
    def list(self) -> list[Webhook]: ...
    def put(self, webhook: Webhook) -> None: ...


class WebhookDeliveryRepository(Protocol):
    def get(self, webhook_delivery_id: str) -> WebhookDelivery | None: ...
    def list(
        self,
        *,
        webhook_id: str | None = None,
        event_id: str | None = None,
        status: str | None = None,
        resource_type: str | None = None,
        resource_id: str | None = None,
    ) -> list[WebhookDelivery]: ...
    def put(self, delivery: WebhookDelivery) -> None: ...


class Clock(Protocol):
    def now(self) -> str: ...


class IdGenerator(Protocol):
    def new_id(self) -> str: ...
